project:
  type: website
  output-dir: docs

website:
  title: "Analysing survey data with complex sampling in R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - data.qmd
      - part-1.qmd
      - part-2.qmd
      - icon: github
        href: https://github.com/mbunk
      - icon: twitter
        href: https://x.com/maddibunker

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
